src/interface_adapter/ViewProfile/ViewProfileController.java
src/interface_adapter/ViewProfile/ViewProfilePresenter.java
src/interface_adapter/ViewProfile/ViewProfileState.java
src/interface_adapter/ViewProfile/ViewProfileViewModel.java
src/use_case/ViewProfile/ViewProfile.java
src/use_case/ViewProfile/ViewProfileDataAccessInterface.java
src/use_case/ViewProfile/ViewProfileInputBoundary.java
src/use_case/ViewProfile/ViewProfileInputData.java
src/use_case/ViewProfile/ViewProfileInteractor.java
src/use_case/ViewProfile/ViewProfileInterface.java
src/use_case/ViewProfile/ViewProfileOutputBoundary.java
src/use_case/ViewProfile/ViewProfileOutputData.java
src/view/SelfProfileView.java

Finish the ViewProfile usecase which is including Inputdata, InputBoundary, Outputdata, OutputBoundary, AccessInterface, Interactor.
Update the interface Adapter package used on ViewProfile which is including Controller, Presenter, Viewmodel and State. 
ViewProfile need an input User user and output the user's String user_id and String nickname.

Userprofile view

---

src/view/LoginView.java

Tried to complete the login view by connecting it to the login controller and login view model, which can let the user login successfully or fail to login after entering their user information. But requires further changes because some errors are occurring in the signup view class.

modified LoginView and try to link it to login controller

---

src/view/ChannelView.java

Move the position of the button from lower-right to upper- right, added new button edit for future usecase of profile view.

moved button position, and added new button

---

src/app/LoginUsecaseFactory.java
src/app/Main.java
src/app/SignupUsecaseFactory.java
src/data_access/FileChannelDataAccessObject.java
src/data_access/FileUserDataAccessObject.java
src/data_access/Main.java
src/interface_adapter/Login/LoginPresenter.java
src/interface_adapter/Login/LoginViewModel.java
src/interface_adapter/logged_in/LoggedInViewModel.java
src/use_case/Login/LoginDataAccessInterface.java
src/use_case/Login/LoginInteractor.java
src/use_case/Signup/SignupDataAccessInterface.java
src/use_case/Signup/SignupInteractor.java
src/view/CreateChannelView.java
src/view/LoginView.java
src/view/SignUpView.java
src/view/ViewManager.java

Add User DAO implements direct DAI
send API request to sendbird to create users and view user
Signuplink and Loginview extends Jpanel and shown on Jframe on app/Main

Sign up debug

---

src/view/CreateChannelView.java

I made minor modifications to createchannelview, addressing the issue where the textfield was covering the label. I also added a main function for preview purposes. Please note that the main function will be removed in the future.

revised createChannelVIew

---

src/interface_adapter/Menu/MenuViewModel.java
src/interface_adapter/list_Channel/ChannelInfo.java
src/interface_adapter/list_Channel/ListChannelController.java
src/interface_adapter/list_Channel/ListChannelPresenter.java
src/interface_adapter/list_Channel/ListChannelState.java
src/interface_adapter/list_Channel/ListChannelViewModel.java

MenuViewmodel, contains a method of getChannelNameList as well as part of the listChannel interface adpater

MenuViewmodel, contains a method of getChannelNameList

---

src/use_case/Login/LoginInteractor.java

log-in interactor debug

---

src/app/Main.java
src/app/SignupUsecaseFactory.java
src/interface_adapter/Signup/SignupPresenter.java
src/interface_adapter/list_Channel/ChannelInfo.java
src/interface_adapter/list_Channel/ListChannelController.java
src/interface_adapter/list_Channel/ListChannelPresenter.java
src/interface_adapter/list_Channel/ListChannelState.java
src/interface_adapter/list_Channel/ListChannelViewModel.java
src/view/LoginView.java
src/view/MenuView.java
src/view/SignUpView.java

changed main function. set the minimum size of main, delete all the frame thing in sign up view and login view.

changed view

---

src/interface_adapter/Login/LoginState.java
src/interface_adapter/UserCreationFailed.java

updated the fail view when user already exists in signup, user doesn't exist in login, and user ID and nickname doesn't match in login.

failed views updated

---

src/app/LoginUsecaseFactory.java
src/app/Main.java
src/interface_adapter/Login/LoginPresenter.java
src/interface_adapter/Menu/MenuViewModel.java
src/interface_adapter/Signup/SignupPresenter.java

Connected Signup view and login view, and menu view.
The loginin presenter is added to a new parameter==menuviewmodel.
Makes menuView model extends viewModel

The signup view and login view are connected.

---

src/use_case/Login/LoginInteractor.java

fixed the bug in LoginInteractor which related to the matching problem of ID and nickname.

Fail views

---

src/data_access/FileUserDataAccessObject.java

list channel DAO debug

---

src/use_case/Signup/SignupInteractor.java
src/view/LoginView.java
src/view/SignUpView.java

Modified the input fields and label distributions in login and signup view, also create another fail view for signing up in sign up interactior, or else after entering empty id or nickname will also be count as success view and be switched to login directly.

Input field modify

---

src/app/Main.java
src/app/MenuViewFactory.java
src/data_access/FileChannelDataAccessObject.java
src/interface_adapter/Login/LoginPresenter.java
src/interface_adapter/Menu/MenuViewModel.java
src/interface_adapter/create_channel/CreateChannelPresenter.java
src/interface_adapter/list_Channel/ListChannelPresenter.java
src/interface_adapter/list_Channel/ListChannelViewModel.java
src/use_case/CreateChannel/CreateChannelInteractor.java
src/use_case/CreateChannel/CreateChannelOutputBoundary.java
src/view/MenuView.java

Updates the presenter for create channel, a MenuViewFactory helps to create menuview, connect the login to the menu view. If login successfully, go to menu view.

Connect the login and menu view

---

src/app/MenuViewFactory.java
src/use_case/CreateChannel/CreateChannelInteractor.java

Some minor resvise. Just for everyone to be updated. Add actionliestener to menuview, will pass the userID iinformation to the state for the createChannel.

Add actionliestener to menuview.

---

src/app/Main.java
src/interface_adapter/Login/LoginPresenter.java
src/interface_adapter/Menu/MenuViewModel.java
src/interface_adapter/create_channel/CreateChannelPresenter.java
src/use_case/CreateChannel/CreateChannelInteractor.java
src/view/CreateChannelView.java
src/view/MenuView.java

connect the menu view and create channel view. If successfully creat…ed a channel, the view will be switched back to menu view and pop up a window says success. otherwise, the view will remain in create channl view and a pop up window says failed

Create Channel usecase and view completely finished.

---

src/data_access/SendMessageDataAccessObject.java
src/entity/Message/CommonMessage.java
src/entity/Message/CommonMessageFactory.java
src/entity/Message/Message.java
src/entity/Message/MessageFactory.java
src/interface_adapter/create_channel/CreateChannelState.java

Changes the message entity, add createAt attribute which is a long indicates the time when the message is sent. Add sendmessage DAO.

Message entity changed

---

src/data_access/FileUserDataAccessObject.java
src/interface_adapter/Menu/MenuViewModel.java
src/interface_adapter/create_channel/CreateChannelPresenter.java
src/interface_adapter/list_Channel/ListChannelPresenter.java
src/interface_adapter/list_Channel/ListChannelState.java
src/interface_adapter/list_Channel/ListChannelViewModel.java
src/use_case/CreateChannel/CreateChannelInteractor.java
src/use_case/CreateChannel/CreateChannelOutputData.java
src/view/MenuView.java
src/view/SelfProfileView.java

List channel usecase finished. after login, the channel that the user is in will be shown on the menu, and everytime after a new channel is created, it will shown on the menu

List channel sue case

---

src/data_access/FileChannelDataAccessObject.java
src/entity/Channel/Channel.java
src/entity/Channel/ChannelFactory.java
src/entity/Channel/CommonChannel.java
src/entity/Channel/CommonChannelFactory.java
src/interface_adapter/create_channel/CreateChannelPresenter.java
src/use_case/CreateChannel/CreateChannelInteractor.java
src/use_case/GetOperator/GetOperatorDataAccessInterface.java
src/use_case/ViewChannel/Test.java
src/use_case/ViewChannel/ViewChannelDataAccessInterface.java
src/use_case/ViewChannel/ViewChannelInputBoundary.java
src/use_case/ViewChannel/ViewChannelInputData.java
src/use_case/ViewChannel/ViewChannelInteractor.java
src/use_case/ViewChannel/ViewChannelOutputBoundary.java
src/use_case/ViewChannel/ViewChannelOutputData.java
src/use_case/ViewMembers/ViewMembersDataAccessInterface.java

created view channel use case that can let user find the channel they are in, we can use it to locate the exact channel view user want to open

created view channel use case

---

src/data_access/FileUserDataAccessObject.java
src/interface_adapter/Invite_Member/InviteMemberController.java
src/interface_adapter/Invite_Member/InviteMemberPresenter.java
src/interface_adapter/Remove_Member/RemoveMemberController.java
src/interface_adapter/Remove_Member/RemoveMemberPresenter.java
src/use_case/InviteMember/InviteMemberDataAccessInterface.java
src/use_case/InviteMember/InviteMemberInteractor.java

Invite and Remove members presenter and controller finish
debug some DAO and invite member usercase interactor
the presenter is half-completed since their viewmodel not complete yet

Invite and Remove members presenter and controller finish

---

src/app/Main.java
src/app/Sounds.java
src/data_access/SendMessageDataAccessObject.java
src/interface_adapter/Channel/ChannelViewModel.java
src/interface_adapter/send_message/SendMessagePresenter.java
src/interface_adapter/translation/TranslatePresenter.java
src/use_case/translate/TranslateInteractor.java
src/view/ChannelView.java

Bug fixing, and translation improved.
The bug fixed is that, every 2.4 sencond, the receive message controller will drag all the messages from the api. I make it as only request the messages after last message ts, and if the channel is just open, it will load 200 messages from now.
The translation usecase is improved, this time it will only translate the slacted language, so that it will not take that long time.
improve the error message and guide for sending message. if a message cann't be sent, a pop up will notice the sender that the sender might have been removed from the channel, or wrong format

Bug fixing

---

.idea/inspectionProfiles/Project_Default.xml
src/TEST/Test.java
src/data_access/FileUserDataAccessObject.java

Add the following test method:
Create User
Login User
Create Channel
View Channel
Send Message
Invite members

Write main test method to the 6 use cases:
